# Generated by Django 3.0.1 on 2021-01-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(db_index=True, max_length=200)),
                ('areasqm', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='realestates/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestates', to='realestate_store.Type')),
            ],
            options={
                'verbose_name_plural': 'realestates',
                'ordering': ('sity', 'address'),
                'index_together': {('id', 'type')},
            },
        ),
    ]
