# Generated by Django 3.0.1 on 2021-01-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
